version: '3.3'

services:
  myapp:
    image: 'docker.io/bitnami/codeigniter:3-debian-10'
    ports:
      - 8000:8000
    volumes:
      - ./CI:/app
    depends_on:
      - db

  db:
    image: mysql
    volumes:
      - ./sql/wis.sql:/docker-entrypoint-initdb.d/
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ' '
      MYSQL_DATABASE: 'wis'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'bbf6e0089638ea61'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    